# coding: utf-8

"""
    ComicVine API

    OpenAPI specification for the ComicVine API  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from comicvine_client.configuration import Configuration


class CharacterAllOf(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'character_enemies': 'list[Character]',
        'character_friends': 'list[Character]',
        'creators': 'list[Person]',
        'first_appeared_in_issue': 'Issue',
        'issues_died_in': 'list[Issue]',
        'movies': 'list[object]',
        'origin': 'object',
        'powers': 'object',
        'publisher': 'object',
        'real_name': 'str',
        'team_enemies': 'list[object]',
        'team_friends': 'list[object]',
        'teams': 'list[object]'
    }

    attribute_map = {
        'character_enemies': 'character_enemies',
        'character_friends': 'character_friends',
        'creators': 'creators',
        'first_appeared_in_issue': 'first_appeared_in_issue',
        'issues_died_in': 'issues_died_in',
        'movies': 'movies',
        'origin': 'origin',
        'powers': 'powers',
        'publisher': 'publisher',
        'real_name': 'real_name',
        'team_enemies': 'team_enemies',
        'team_friends': 'team_friends',
        'teams': 'teams'
    }

    def __init__(self, character_enemies=None, character_friends=None, creators=None, first_appeared_in_issue=None, issues_died_in=None, movies=None, origin=None, powers=None, publisher=None, real_name=None, team_enemies=None, team_friends=None, teams=None, local_vars_configuration=None):  # noqa: E501
        """CharacterAllOf - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._character_enemies = None
        self._character_friends = None
        self._creators = None
        self._first_appeared_in_issue = None
        self._issues_died_in = None
        self._movies = None
        self._origin = None
        self._powers = None
        self._publisher = None
        self._real_name = None
        self._team_enemies = None
        self._team_friends = None
        self._teams = None
        self.discriminator = None

        if character_enemies is not None:
            self.character_enemies = character_enemies
        if character_friends is not None:
            self.character_friends = character_friends
        if creators is not None:
            self.creators = creators
        if first_appeared_in_issue is not None:
            self.first_appeared_in_issue = first_appeared_in_issue
        if issues_died_in is not None:
            self.issues_died_in = issues_died_in
        if movies is not None:
            self.movies = movies
        if origin is not None:
            self.origin = origin
        if powers is not None:
            self.powers = powers
        if publisher is not None:
            self.publisher = publisher
        if real_name is not None:
            self.real_name = real_name
        if team_enemies is not None:
            self.team_enemies = team_enemies
        if team_friends is not None:
            self.team_friends = team_friends
        if teams is not None:
            self.teams = teams

    @property
    def character_enemies(self):
        """Gets the character_enemies of this CharacterAllOf.  # noqa: E501


        :return: The character_enemies of this CharacterAllOf.  # noqa: E501
        :rtype: list[Character]
        """
        return self._character_enemies

    @character_enemies.setter
    def character_enemies(self, character_enemies):
        """Sets the character_enemies of this CharacterAllOf.


        :param character_enemies: The character_enemies of this CharacterAllOf.  # noqa: E501
        :type character_enemies: list[Character]
        """

        self._character_enemies = character_enemies

    @property
    def character_friends(self):
        """Gets the character_friends of this CharacterAllOf.  # noqa: E501


        :return: The character_friends of this CharacterAllOf.  # noqa: E501
        :rtype: list[Character]
        """
        return self._character_friends

    @character_friends.setter
    def character_friends(self, character_friends):
        """Sets the character_friends of this CharacterAllOf.


        :param character_friends: The character_friends of this CharacterAllOf.  # noqa: E501
        :type character_friends: list[Character]
        """

        self._character_friends = character_friends

    @property
    def creators(self):
        """Gets the creators of this CharacterAllOf.  # noqa: E501


        :return: The creators of this CharacterAllOf.  # noqa: E501
        :rtype: list[Person]
        """
        return self._creators

    @creators.setter
    def creators(self, creators):
        """Sets the creators of this CharacterAllOf.


        :param creators: The creators of this CharacterAllOf.  # noqa: E501
        :type creators: list[Person]
        """

        self._creators = creators

    @property
    def first_appeared_in_issue(self):
        """Gets the first_appeared_in_issue of this CharacterAllOf.  # noqa: E501


        :return: The first_appeared_in_issue of this CharacterAllOf.  # noqa: E501
        :rtype: Issue
        """
        return self._first_appeared_in_issue

    @first_appeared_in_issue.setter
    def first_appeared_in_issue(self, first_appeared_in_issue):
        """Sets the first_appeared_in_issue of this CharacterAllOf.


        :param first_appeared_in_issue: The first_appeared_in_issue of this CharacterAllOf.  # noqa: E501
        :type first_appeared_in_issue: Issue
        """

        self._first_appeared_in_issue = first_appeared_in_issue

    @property
    def issues_died_in(self):
        """Gets the issues_died_in of this CharacterAllOf.  # noqa: E501


        :return: The issues_died_in of this CharacterAllOf.  # noqa: E501
        :rtype: list[Issue]
        """
        return self._issues_died_in

    @issues_died_in.setter
    def issues_died_in(self, issues_died_in):
        """Sets the issues_died_in of this CharacterAllOf.


        :param issues_died_in: The issues_died_in of this CharacterAllOf.  # noqa: E501
        :type issues_died_in: list[Issue]
        """

        self._issues_died_in = issues_died_in

    @property
    def movies(self):
        """Gets the movies of this CharacterAllOf.  # noqa: E501

        Movies the character was in.  # noqa: E501

        :return: The movies of this CharacterAllOf.  # noqa: E501
        :rtype: list[object]
        """
        return self._movies

    @movies.setter
    def movies(self, movies):
        """Sets the movies of this CharacterAllOf.

        Movies the character was in.  # noqa: E501

        :param movies: The movies of this CharacterAllOf.  # noqa: E501
        :type movies: list[object]
        """

        self._movies = movies

    @property
    def origin(self):
        """Gets the origin of this CharacterAllOf.  # noqa: E501

        The origin of the character. Human, Alien, Robot ...etc  # noqa: E501

        :return: The origin of this CharacterAllOf.  # noqa: E501
        :rtype: object
        """
        return self._origin

    @origin.setter
    def origin(self, origin):
        """Sets the origin of this CharacterAllOf.

        The origin of the character. Human, Alien, Robot ...etc  # noqa: E501

        :param origin: The origin of this CharacterAllOf.  # noqa: E501
        :type origin: object
        """

        self._origin = origin

    @property
    def powers(self):
        """Gets the powers of this CharacterAllOf.  # noqa: E501

        List of super powers a character has.  # noqa: E501

        :return: The powers of this CharacterAllOf.  # noqa: E501
        :rtype: object
        """
        return self._powers

    @powers.setter
    def powers(self, powers):
        """Sets the powers of this CharacterAllOf.

        List of super powers a character has.  # noqa: E501

        :param powers: The powers of this CharacterAllOf.  # noqa: E501
        :type powers: object
        """

        self._powers = powers

    @property
    def publisher(self):
        """Gets the publisher of this CharacterAllOf.  # noqa: E501

        The primary publisher a character is attached to.  # noqa: E501

        :return: The publisher of this CharacterAllOf.  # noqa: E501
        :rtype: object
        """
        return self._publisher

    @publisher.setter
    def publisher(self, publisher):
        """Sets the publisher of this CharacterAllOf.

        The primary publisher a character is attached to.  # noqa: E501

        :param publisher: The publisher of this CharacterAllOf.  # noqa: E501
        :type publisher: object
        """

        self._publisher = publisher

    @property
    def real_name(self):
        """Gets the real_name of this CharacterAllOf.  # noqa: E501

        Real name of the character.  # noqa: E501

        :return: The real_name of this CharacterAllOf.  # noqa: E501
        :rtype: str
        """
        return self._real_name

    @real_name.setter
    def real_name(self, real_name):
        """Sets the real_name of this CharacterAllOf.

        Real name of the character.  # noqa: E501

        :param real_name: The real_name of this CharacterAllOf.  # noqa: E501
        :type real_name: str
        """

        self._real_name = real_name

    @property
    def team_enemies(self):
        """Gets the team_enemies of this CharacterAllOf.  # noqa: E501

        List of teams that are enemies of this character.  # noqa: E501

        :return: The team_enemies of this CharacterAllOf.  # noqa: E501
        :rtype: list[object]
        """
        return self._team_enemies

    @team_enemies.setter
    def team_enemies(self, team_enemies):
        """Sets the team_enemies of this CharacterAllOf.

        List of teams that are enemies of this character.  # noqa: E501

        :param team_enemies: The team_enemies of this CharacterAllOf.  # noqa: E501
        :type team_enemies: list[object]
        """

        self._team_enemies = team_enemies

    @property
    def team_friends(self):
        """Gets the team_friends of this CharacterAllOf.  # noqa: E501

        List of teams that are friends with this character.  # noqa: E501

        :return: The team_friends of this CharacterAllOf.  # noqa: E501
        :rtype: list[object]
        """
        return self._team_friends

    @team_friends.setter
    def team_friends(self, team_friends):
        """Sets the team_friends of this CharacterAllOf.

        List of teams that are friends with this character.  # noqa: E501

        :param team_friends: The team_friends of this CharacterAllOf.  # noqa: E501
        :type team_friends: list[object]
        """

        self._team_friends = team_friends

    @property
    def teams(self):
        """Gets the teams of this CharacterAllOf.  # noqa: E501

        List of teams this character is a member of.  # noqa: E501

        :return: The teams of this CharacterAllOf.  # noqa: E501
        :rtype: list[object]
        """
        return self._teams

    @teams.setter
    def teams(self, teams):
        """Sets the teams of this CharacterAllOf.

        List of teams this character is a member of.  # noqa: E501

        :param teams: The teams of this CharacterAllOf.  # noqa: E501
        :type teams: list[object]
        """

        self._teams = teams

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, CharacterAllOf):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, CharacterAllOf):
            return True

        return self.to_dict() != other.to_dict()
