# coding: utf-8

"""
    ComicVine API

    OpenAPI specification for the ComicVine API  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from comicvine_client.configuration import Configuration


class VolumeAllOf(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'aliases': 'str',
        'characters': 'list[object]',
        'concepts': 'list[object]',
        'count_of_issues': 'int',
        'first_issue': 'object',
        'image': 'object',
        'last_issue': 'object',
        'location_credits': 'object',
        'object_credits': 'object',
        'person_credits': 'object',
        'publisher': 'object',
        'start_year': 'str',
        'team_credits': 'object'
    }

    attribute_map = {
        'aliases': 'aliases',
        'characters': 'characters',
        'concepts': 'concepts',
        'count_of_issues': 'count_of_issues',
        'first_issue': 'first_issue',
        'image': 'image',
        'last_issue': 'last_issue',
        'location_credits': 'location_credits',
        'object_credits': 'object_credits',
        'person_credits': 'person_credits',
        'publisher': 'publisher',
        'start_year': 'start_year',
        'team_credits': 'team_credits'
    }

    def __init__(self, aliases=None, characters=None, concepts=None, count_of_issues=None, first_issue=None, image=None, last_issue=None, location_credits=None, object_credits=None, person_credits=None, publisher=None, start_year=None, team_credits=None, local_vars_configuration=None):  # noqa: E501
        """VolumeAllOf - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._aliases = None
        self._characters = None
        self._concepts = None
        self._count_of_issues = None
        self._first_issue = None
        self._image = None
        self._last_issue = None
        self._location_credits = None
        self._object_credits = None
        self._person_credits = None
        self._publisher = None
        self._start_year = None
        self._team_credits = None
        self.discriminator = None

        if aliases is not None:
            self.aliases = aliases
        if characters is not None:
            self.characters = characters
        if concepts is not None:
            self.concepts = concepts
        if count_of_issues is not None:
            self.count_of_issues = count_of_issues
        if first_issue is not None:
            self.first_issue = first_issue
        if image is not None:
            self.image = image
        if last_issue is not None:
            self.last_issue = last_issue
        if location_credits is not None:
            self.location_credits = location_credits
        if object_credits is not None:
            self.object_credits = object_credits
        if person_credits is not None:
            self.person_credits = person_credits
        if publisher is not None:
            self.publisher = publisher
        if start_year is not None:
            self.start_year = start_year
        if team_credits is not None:
            self.team_credits = team_credits

    @property
    def aliases(self):
        """Gets the aliases of this VolumeAllOf.  # noqa: E501

        List of aliases the volume is known by. A \\n (newline) seperates each alias.  # noqa: E501

        :return: The aliases of this VolumeAllOf.  # noqa: E501
        :rtype: str
        """
        return self._aliases

    @aliases.setter
    def aliases(self, aliases):
        """Sets the aliases of this VolumeAllOf.

        List of aliases the volume is known by. A \\n (newline) seperates each alias.  # noqa: E501

        :param aliases: The aliases of this VolumeAllOf.  # noqa: E501
        :type: str
        """

        self._aliases = aliases

    @property
    def characters(self):
        """Gets the characters of this VolumeAllOf.  # noqa: E501

        A list of characters that appear in this volume.  # noqa: E501

        :return: The characters of this VolumeAllOf.  # noqa: E501
        :rtype: list[object]
        """
        return self._characters

    @characters.setter
    def characters(self, characters):
        """Sets the characters of this VolumeAllOf.

        A list of characters that appear in this volume.  # noqa: E501

        :param characters: The characters of this VolumeAllOf.  # noqa: E501
        :type: list[object]
        """

        self._characters = characters

    @property
    def concepts(self):
        """Gets the concepts of this VolumeAllOf.  # noqa: E501

        A list of concepts that appear in this volume.  # noqa: E501

        :return: The concepts of this VolumeAllOf.  # noqa: E501
        :rtype: list[object]
        """
        return self._concepts

    @concepts.setter
    def concepts(self, concepts):
        """Sets the concepts of this VolumeAllOf.

        A list of concepts that appear in this volume.  # noqa: E501

        :param concepts: The concepts of this VolumeAllOf.  # noqa: E501
        :type: list[object]
        """

        self._concepts = concepts

    @property
    def count_of_issues(self):
        """Gets the count_of_issues of this VolumeAllOf.  # noqa: E501

        Number of issues included in this volume.  # noqa: E501

        :return: The count_of_issues of this VolumeAllOf.  # noqa: E501
        :rtype: int
        """
        return self._count_of_issues

    @count_of_issues.setter
    def count_of_issues(self, count_of_issues):
        """Sets the count_of_issues of this VolumeAllOf.

        Number of issues included in this volume.  # noqa: E501

        :param count_of_issues: The count_of_issues of this VolumeAllOf.  # noqa: E501
        :type: int
        """

        self._count_of_issues = count_of_issues

    @property
    def first_issue(self):
        """Gets the first_issue of this VolumeAllOf.  # noqa: E501

        The first issue in this volume.  # noqa: E501

        :return: The first_issue of this VolumeAllOf.  # noqa: E501
        :rtype: object
        """
        return self._first_issue

    @first_issue.setter
    def first_issue(self, first_issue):
        """Sets the first_issue of this VolumeAllOf.

        The first issue in this volume.  # noqa: E501

        :param first_issue: The first_issue of this VolumeAllOf.  # noqa: E501
        :type: object
        """

        self._first_issue = first_issue

    @property
    def image(self):
        """Gets the image of this VolumeAllOf.  # noqa: E501

        Main image of the volume.  # noqa: E501

        :return: The image of this VolumeAllOf.  # noqa: E501
        :rtype: object
        """
        return self._image

    @image.setter
    def image(self, image):
        """Sets the image of this VolumeAllOf.

        Main image of the volume.  # noqa: E501

        :param image: The image of this VolumeAllOf.  # noqa: E501
        :type: object
        """

        self._image = image

    @property
    def last_issue(self):
        """Gets the last_issue of this VolumeAllOf.  # noqa: E501

        The last issue in this volume.  # noqa: E501

        :return: The last_issue of this VolumeAllOf.  # noqa: E501
        :rtype: object
        """
        return self._last_issue

    @last_issue.setter
    def last_issue(self, last_issue):
        """Sets the last_issue of this VolumeAllOf.

        The last issue in this volume.  # noqa: E501

        :param last_issue: The last_issue of this VolumeAllOf.  # noqa: E501
        :type: object
        """

        self._last_issue = last_issue

    @property
    def location_credits(self):
        """Gets the location_credits of this VolumeAllOf.  # noqa: E501

        List of locations that appeared in this volume.  # noqa: E501

        :return: The location_credits of this VolumeAllOf.  # noqa: E501
        :rtype: object
        """
        return self._location_credits

    @location_credits.setter
    def location_credits(self, location_credits):
        """Sets the location_credits of this VolumeAllOf.

        List of locations that appeared in this volume.  # noqa: E501

        :param location_credits: The location_credits of this VolumeAllOf.  # noqa: E501
        :type: object
        """

        self._location_credits = location_credits

    @property
    def object_credits(self):
        """Gets the object_credits of this VolumeAllOf.  # noqa: E501

        List of objects that appeared in this volume.  # noqa: E501

        :return: The object_credits of this VolumeAllOf.  # noqa: E501
        :rtype: object
        """
        return self._object_credits

    @object_credits.setter
    def object_credits(self, object_credits):
        """Sets the object_credits of this VolumeAllOf.

        List of objects that appeared in this volume.  # noqa: E501

        :param object_credits: The object_credits of this VolumeAllOf.  # noqa: E501
        :type: object
        """

        self._object_credits = object_credits

    @property
    def person_credits(self):
        """Gets the person_credits of this VolumeAllOf.  # noqa: E501

        List of people that worked on this volume.  # noqa: E501

        :return: The person_credits of this VolumeAllOf.  # noqa: E501
        :rtype: object
        """
        return self._person_credits

    @person_credits.setter
    def person_credits(self, person_credits):
        """Sets the person_credits of this VolumeAllOf.

        List of people that worked on this volume.  # noqa: E501

        :param person_credits: The person_credits of this VolumeAllOf.  # noqa: E501
        :type: object
        """

        self._person_credits = person_credits

    @property
    def publisher(self):
        """Gets the publisher of this VolumeAllOf.  # noqa: E501

        The primary publisher a volume is attached to.  # noqa: E501

        :return: The publisher of this VolumeAllOf.  # noqa: E501
        :rtype: object
        """
        return self._publisher

    @publisher.setter
    def publisher(self, publisher):
        """Sets the publisher of this VolumeAllOf.

        The primary publisher a volume is attached to.  # noqa: E501

        :param publisher: The publisher of this VolumeAllOf.  # noqa: E501
        :type: object
        """

        self._publisher = publisher

    @property
    def start_year(self):
        """Gets the start_year of this VolumeAllOf.  # noqa: E501

        The first year this volume appeared in comics.  # noqa: E501

        :return: The start_year of this VolumeAllOf.  # noqa: E501
        :rtype: str
        """
        return self._start_year

    @start_year.setter
    def start_year(self, start_year):
        """Sets the start_year of this VolumeAllOf.

        The first year this volume appeared in comics.  # noqa: E501

        :param start_year: The start_year of this VolumeAllOf.  # noqa: E501
        :type: str
        """

        self._start_year = start_year

    @property
    def team_credits(self):
        """Gets the team_credits of this VolumeAllOf.  # noqa: E501

        List of teams that appear in this volume.  # noqa: E501

        :return: The team_credits of this VolumeAllOf.  # noqa: E501
        :rtype: object
        """
        return self._team_credits

    @team_credits.setter
    def team_credits(self, team_credits):
        """Sets the team_credits of this VolumeAllOf.

        List of teams that appear in this volume.  # noqa: E501

        :param team_credits: The team_credits of this VolumeAllOf.  # noqa: E501
        :type: object
        """

        self._team_credits = team_credits

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, VolumeAllOf):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, VolumeAllOf):
            return True

        return self.to_dict() != other.to_dict()
