# coding: utf-8

"""
    ComicVine API

    OpenAPI specification for the ComicVine API  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import comicvine_client
from comicvine_client.models.base_entity import BaseEntity  # noqa: E501
from comicvine_client.rest import ApiException

class TestBaseEntity(unittest.TestCase):
    """BaseEntity unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test BaseEntity
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = comicvine_client.models.base_entity.BaseEntity()  # noqa: E501
        if include_optional :
            return BaseEntity(
                id = 63316, 
                name = "Yoko Tsuno", 
                aliases = "Joko Zuno", 
                api_detail_url = "https://comicvine.gamespot.com/api/volume/4050-87668/", 
                site_detail_url = "https://comicvine.gamespot.com/yoko-tsuno/4005-63316/", 
                date_added = "2016-01-26 17:52:32", 
                date_last_updated = "2016-01-26 17:53:02"
            )
        else :
            return BaseEntity(
                id = 63316,
        )

    def testBaseEntity(self):
        """Test BaseEntity"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
