# coding: utf-8

"""
    ComicVine API

    OpenAPI specification for the ComicVine API  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import comicvine_client
from comicvine_client.models.volume_all_of import VolumeAllOf  # noqa: E501
from comicvine_client.rest import ApiException

class TestVolumeAllOf(unittest.TestCase):
    """VolumeAllOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test VolumeAllOf
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = comicvine_client.models.volume_all_of.VolumeAllOf()  # noqa: E501
        if include_optional :
            return VolumeAllOf(
                characters = [
                    None
                    ], 
                concepts = [
                    None
                    ], 
                count_of_issues = 13, 
                first_issue = null, 
                image = comicvine_client.models.image.Image(
                    icon_url = 'https://comicvine1.cbsistatic.com/uploads/square_avatar/5/53387/2638218-2638217-1_nl_v02.jpg', 
                    medium_url = 'https://comicvine1.cbsistatic.com/uploads/scale_medium/5/53387/2638218-2638217-1_nl_v02.jpg', 
                    screen_url = 'https://comicvine1.cbsistatic.com/uploads/screen_medium/5/53387/2638218-2638217-1_nl_v02.jpg', 
                    screen_large_url = 'https://comicvine1.cbsistatic.com/uploads/screen_kubrick/5/53387/2638218-2638217-1_nl_v02.jpg', 
                    small_url = 'https://comicvine1.cbsistatic.com/uploads/scale_small/5/53387/2638218-2638217-1_nl_v02.jpg', 
                    super_url = 'https://comicvine1.cbsistatic.com/uploads/scale_large/5/53387/2638218-2638217-1_nl_v02.jpg', 
                    thumb_url = 'https://comicvine1.cbsistatic.com/uploads/scale_avatar/5/53387/2638218-2638217-1_nl_v02.jpg', 
                    tiny_url = 'https://comicvine1.cbsistatic.com/uploads/square_mini/5/53387/2638218-2638217-1_nl_v02.jpg', 
                    original_url = 'https://comicvine1.cbsistatic.com/uploads/original/5/53387/2638218-2638217-1_nl_v02.jpg', 
                    image_tags = 'All Images', ), 
                last_issue = null, 
                locations = [
                    None
                    ], 
                objects = [
                    None
                    ], 
                people = [
                    None
                    ], 
                publisher = None, 
                start_year = '2007'
            )
        else :
            return VolumeAllOf(
        )

    def testVolumeAllOf(self):
        """Test VolumeAllOf"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
