# coding: utf-8

"""
    ComicVine API

    OpenAPI specification for the ComicVine API  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import comicvine_client
from comicvine_client.models.issue_all_of import IssueAllOf  # noqa: E501
from comicvine_client.rest import ApiException

class TestIssueAllOf(unittest.TestCase):
    """IssueAllOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test IssueAllOf
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = comicvine_client.models.issue_all_of.IssueAllOf()  # noqa: E501
        if include_optional :
            return IssueAllOf(
                character_credits = [
                    null
                    ], 
                characters_died_in = [
                    null
                    ], 
                concept_credits = [
                    None
                    ], 
                cover_date = 'Tue Jan 31 00:00:00 GMT 1995', 
                disbanded_teams = [
                    None
                    ], 
                first_appearance_characters = [
                    null
                    ], 
                first_appearance_concepts = [
                    None
                    ], 
                first_appearance_locations = [
                    None
                    ], 
                first_appearance_objects = [
                    None
                    ], 
                first_appearance_storyarcs = [
                    None
                    ], 
                first_appearance_teams = None, 
                has_staff_review = True, 
                issue_number = '0', 
                location_credits = [
                    None
                    ], 
                object_credits = [
                    None
                    ], 
                person_credits = [
                    null
                    ], 
                store_date = 'Tue Jan 31 00:00:00 GMT 1995', 
                story_arc_credits = [
                    None
                    ], 
                team_credits = [
                    None
                    ], 
                teams_disbanded_in = [
                    None
                    ], 
                volume = null
            )
        else :
            return IssueAllOf(
        )

    def testIssueAllOf(self):
        """Test IssueAllOf"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
