# coding: utf-8

"""
    ComicVine API

    OpenAPI specification for the ComicVine API  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import comicvine_client
from comicvine_client.models.base_person_all_of import BasePersonAllOf  # noqa: E501
from comicvine_client.rest import ApiException

class TestBasePersonAllOf(unittest.TestCase):
    """BasePersonAllOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test BasePersonAllOf
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = comicvine_client.models.base_person_all_of.BasePersonAllOf()  # noqa: E501
        if include_optional :
            return BasePersonAllOf(
                birth = 'Feb 19, 1972', 
                count_of_issue_appearances = 17949, 
                gender = 3, 
                story_arc_credits = [
                    None
                    ], 
                volume_credits = [
                    null
                    ], 
                issue_credits = [
                    null
                    ]
            )
        else :
            return BasePersonAllOf(
        )

    def testBasePersonAllOf(self):
        """Test BasePersonAllOf"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
