# coding: utf-8

"""
    ComicVine API

    OpenAPI specification for the ComicVine API  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import comicvine_client
from comicvine_client.models.issue_all_of1 import IssueAllOf1  # noqa: E501
from comicvine_client.rest import ApiException

class TestIssueAllOf1(unittest.TestCase):
    """IssueAllOf1 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test IssueAllOf1
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = comicvine_client.models.issue_all_of1.IssueAllOf1()  # noqa: E501
        if include_optional :
            return IssueAllOf1(
                character_credits = null, 
                characters_died_in = null, 
                concept_credits = null, 
                cover_date = null, 
                deck = null, 
                description = null, 
                disbanded_teams = null, 
                first_appearance_characters = null, 
                first_appearance_concepts = null, 
                first_appearance_locations = null, 
                first_appearance_objects = null, 
                first_appearance_storyarcs = null, 
                first_appearance_teams = null, 
                image = null, 
                issue_number = null, 
                location_credits = null, 
                object_credits = null, 
                person_credits = null, 
                store_date = null, 
                story_arc_credits = null, 
                team_credits = null, 
                teams_disbanded_in = null, 
                volume = null
            )
        else :
            return IssueAllOf1(
        )

    def testIssueAllOf1(self):
        """Test IssueAllOf1"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
