# coding: utf-8

"""
    ComicVine API

    OpenAPI specification for the ComicVine API  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import comicvine_client
from comicvine_client.models.volume_all_of import VolumeAllOf  # noqa: E501
from comicvine_client.rest import ApiException

class TestVolumeAllOf(unittest.TestCase):
    """VolumeAllOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test VolumeAllOf
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = comicvine_client.models.volume_all_of.VolumeAllOf()  # noqa: E501
        if include_optional :
            return VolumeAllOf(
                aliases = null, 
                character_credits = null, 
                concept_credits = null, 
                count_of_issues = null, 
                deck = null, 
                description = null, 
                first_issue = null, 
                image = null, 
                last_issue = null, 
                location_credits = null, 
                object_credits = null, 
                person_credits = null, 
                publisher = null, 
                start_year = null, 
                team_credits = null
            )
        else :
            return VolumeAllOf(
        )

    def testVolumeAllOf(self):
        """Test VolumeAllOf"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
