# coding: utf-8

"""
    ComicVine API

    OpenAPI specification for the ComicVine API  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import comicvine_client
from comicvine_client.models.issue_all_of import IssueAllOf  # noqa: E501
from comicvine_client.rest import ApiException

class TestIssueAllOf(unittest.TestCase):
    """IssueAllOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test IssueAllOf
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = comicvine_client.models.issue_all_of.IssueAllOf()  # noqa: E501
        if include_optional :
            return IssueAllOf(
                date_added = None, 
                date_last_updated = None, 
                id = None, 
                aliases = None, 
                api_detail_url = None, 
                site_detail_url = None, 
                name = None, 
                character_credits = None, 
                characters_died_in = None, 
                concept_credits = None, 
                cover_date = None, 
                deck = None, 
                description = None, 
                disbanded_teams = None, 
                first_appearance_characters = None, 
                first_appearance_concepts = None, 
                first_appearance_locations = None, 
                first_appearance_objects = None, 
                first_appearance_storyarcs = None, 
                first_appearance_teams = None, 
                image = None, 
                issue_number = None, 
                location_credits = None, 
                object_credits = None, 
                person_credits = None, 
                store_date = None, 
                story_arc_credits = None, 
                team_credits = None, 
                teams_disbanded_in = None, 
                volume = None
            )
        else :
            return IssueAllOf(
        )

    def testIssueAllOf(self):
        """Test IssueAllOf"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
